### ISSUE TITLE
Css makeover

### ISSUE THREAD

**Issue by PianoPenguin471** [ammonc/wordle-solver#1]
Here is some css that was copied from the wordle website. 
`
div input {
    width: 15%;
    display: inline-flex;
    justify-content: center;
    align-items: center;
    font-size: 2rem;
    line-height: 2rem;
    font-weight: bold;
    vertical-align: middle;
    box-sizing: border-box;
    color: #ffffff;
    text-transform: uppercase;
}
#row_1 input {
    background-color: #6aaa64;
}
#wrong_place input {
    background-color: #c9b458;
}`

**Comment by ammonc** [comment]
Pull request merged
